services:
- type: web
  name: pp-api
  env: node
  rootDir: server/api
  buildCommand: npm install
  startCommand: node index.js
  autoDeploy: true
  envVars:
    - key: DATABASE_URL
      sync: false
    - key: REDIS_URL
      sync: false
    - key: PUBLIC_BASE_URL
      sync: false
    - key: VAPID_PUBLIC_KEY
      sync: false
    - key: VAPID_PRIVATE_KEY
      sync: false
    - key: GOOGLE_CLIENT_ID
      sync: false
    - key: GOOGLE_CLIENT_SECRET
      sync: false
    - key: GITHUB_CLIENT_ID
      sync: false
    - key: GITHUB_CLIENT_SECRET
      sync: false
    - key: OPENAI_API_KEY
      sync: false
    - key: OPENAI_MODEL
      sync: false
    - key: REQUIRE_CONFIRMATIONS
      sync: false
    - key: MAX_ORDER_USD
      sync: false
    - key: KILL_SWITCH
      sync: false
  healthCheckPath: /healthz

- type: worker
  name: pp-worker
  env: node
  rootDir: server/worker
  buildCommand: npm install
  startCommand: node index.js
  autoDeploy: true
  envVars:
    - key: DATABASE_URL
      sync: false
    - key: REDIS_URL
      sync: false
    - key: OPENAI_API_KEY
      sync: false
    - key: OPENAI_MODEL
      sync: false
    - key: MAX_ORDER_USD
      sync: false
    - key: KILL_SWITCH
      sync: false
